version: "3.8"

services:
  localstack:
    container_name: "localstack-nems-event-processor"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=sqs,sns
      - DEFAULT_REGION=eu-west-2
      - HOSTNAME_EXTERNAL=localhost
      - EDGE_PORT=4571
    volumes:
      - "/var/lib/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
