format_version: 4
common:
  common_stages: &common_stages
    - promote_docker_image:
        resources:
          - docker
        clean_workspace: true
        tasks:
          - exec:
              command: /bin/bash
              arguments:
                - -c
                - ./tasks promote_docker_image
    - deploy:
        clean_workspace: true
        resources:
          - docker
        artifacts:
          - build:
              source: terraform/nhs_deployment.tfplan
              destination: terraform/
        tasks:
          - exec:
              command: /bin/bash
              arguments:
                - -c
                - ./tasks tf_plan create
          - exec:
              command: /bin/bash
              arguments:
                - -c
                - ./tasks tf_apply
          - exec:
              command: /bin/bash
              arguments:
                - -c
                - ./tasks wait_ecs
pipelines:
  'nems-event-processor.perf':
    group: performance
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
      app:
        pipeline: nems-event-processor
        stage: promote.test
    environment_variables:
      NHS_ENVIRONMENT: perf
    stages: *common_stages
